package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class ActionInfo extends BaseEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column action_info.ACTION_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer actionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column action_info.ACTION_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String actionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column action_info.ACTION_REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String actionRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column action_info.ACTION_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String actionUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column action_info.ACTION_ID
	 * @return  the value of action_info.ACTION_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getActionId() {
		return actionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column action_info.ACTION_ID
	 * @param actionId  the value for action_info.ACTION_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column action_info.ACTION_NAME
	 * @return  the value of action_info.ACTION_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getActionName() {
		return actionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column action_info.ACTION_NAME
	 * @param actionName  the value for action_info.ACTION_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column action_info.ACTION_REMARK
	 * @return  the value of action_info.ACTION_REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getActionRemark() {
		return actionRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column action_info.ACTION_REMARK
	 * @param actionRemark  the value for action_info.ACTION_REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setActionRemark(String actionRemark) {
		this.actionRemark = actionRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column action_info.ACTION_URL
	 * @return  the value of action_info.ACTION_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getActionUrl() {
		return actionUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column action_info.ACTION_URL
	 * @param actionUrl  the value for action_info.ACTION_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setActionUrl(String actionUrl) {
		this.actionUrl = actionUrl;
	}
}