package com.whhft.sysmanage.common.entity;

import java.util.ArrayList;
import java.util.List;

public class DictDefineExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public DictDefineExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDictDefineIdIsNull() {
			addCriterion("DICT_DEFINE_ID is null");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdIsNotNull() {
			addCriterion("DICT_DEFINE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdEqualTo(Integer value) {
			addCriterion("DICT_DEFINE_ID =", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdNotEqualTo(Integer value) {
			addCriterion("DICT_DEFINE_ID <>", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdGreaterThan(Integer value) {
			addCriterion("DICT_DEFINE_ID >", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("DICT_DEFINE_ID >=", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdLessThan(Integer value) {
			addCriterion("DICT_DEFINE_ID <", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdLessThanOrEqualTo(Integer value) {
			addCriterion("DICT_DEFINE_ID <=", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdIn(List<Integer> values) {
			addCriterion("DICT_DEFINE_ID in", values, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdNotIn(List<Integer> values) {
			addCriterion("DICT_DEFINE_ID not in", values, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdBetween(Integer value1, Integer value2) {
			addCriterion("DICT_DEFINE_ID between", value1, value2, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdNotBetween(Integer value1, Integer value2) {
			addCriterion("DICT_DEFINE_ID not between", value1, value2, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyIsNull() {
			addCriterion("DICT_DEFINE_KEY is null");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyIsNotNull() {
			addCriterion("DICT_DEFINE_KEY is not null");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyEqualTo(String value) {
			addCriterion("DICT_DEFINE_KEY =", value, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyNotEqualTo(String value) {
			addCriterion("DICT_DEFINE_KEY <>", value, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyGreaterThan(String value) {
			addCriterion("DICT_DEFINE_KEY >", value, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyGreaterThanOrEqualTo(String value) {
			addCriterion("DICT_DEFINE_KEY >=", value, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyLessThan(String value) {
			addCriterion("DICT_DEFINE_KEY <", value, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyLessThanOrEqualTo(String value) {
			addCriterion("DICT_DEFINE_KEY <=", value, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyLike(String value) {
			addCriterion("DICT_DEFINE_KEY like", value, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyNotLike(String value) {
			addCriterion("DICT_DEFINE_KEY not like", value, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyIn(List<String> values) {
			addCriterion("DICT_DEFINE_KEY in", values, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyNotIn(List<String> values) {
			addCriterion("DICT_DEFINE_KEY not in", values, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyBetween(String value1, String value2) {
			addCriterion("DICT_DEFINE_KEY between", value1, value2, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineKeyNotBetween(String value1, String value2) {
			addCriterion("DICT_DEFINE_KEY not between", value1, value2, "dictDefineKey");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameIsNull() {
			addCriterion("DICT_DEFINE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameIsNotNull() {
			addCriterion("DICT_DEFINE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameEqualTo(String value) {
			addCriterion("DICT_DEFINE_NAME =", value, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameNotEqualTo(String value) {
			addCriterion("DICT_DEFINE_NAME <>", value, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameGreaterThan(String value) {
			addCriterion("DICT_DEFINE_NAME >", value, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameGreaterThanOrEqualTo(String value) {
			addCriterion("DICT_DEFINE_NAME >=", value, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameLessThan(String value) {
			addCriterion("DICT_DEFINE_NAME <", value, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameLessThanOrEqualTo(String value) {
			addCriterion("DICT_DEFINE_NAME <=", value, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameLike(String value) {
			addCriterion("DICT_DEFINE_NAME like", value, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameNotLike(String value) {
			addCriterion("DICT_DEFINE_NAME not like", value, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameIn(List<String> values) {
			addCriterion("DICT_DEFINE_NAME in", values, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameNotIn(List<String> values) {
			addCriterion("DICT_DEFINE_NAME not in", values, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameBetween(String value1, String value2) {
			addCriterion("DICT_DEFINE_NAME between", value1, value2, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineNameNotBetween(String value1, String value2) {
			addCriterion("DICT_DEFINE_NAME not between", value1, value2, "dictDefineName");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeIsNull() {
			addCriterion("DICT_DEFINE_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeIsNotNull() {
			addCriterion("DICT_DEFINE_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeEqualTo(String value) {
			addCriterion("DICT_DEFINE_TYPE =", value, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeNotEqualTo(String value) {
			addCriterion("DICT_DEFINE_TYPE <>", value, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeGreaterThan(String value) {
			addCriterion("DICT_DEFINE_TYPE >", value, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeGreaterThanOrEqualTo(String value) {
			addCriterion("DICT_DEFINE_TYPE >=", value, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeLessThan(String value) {
			addCriterion("DICT_DEFINE_TYPE <", value, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeLessThanOrEqualTo(String value) {
			addCriterion("DICT_DEFINE_TYPE <=", value, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeLike(String value) {
			addCriterion("DICT_DEFINE_TYPE like", value, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeNotLike(String value) {
			addCriterion("DICT_DEFINE_TYPE not like", value, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeIn(List<String> values) {
			addCriterion("DICT_DEFINE_TYPE in", values, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeNotIn(List<String> values) {
			addCriterion("DICT_DEFINE_TYPE not in", values, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeBetween(String value1, String value2) {
			addCriterion("DICT_DEFINE_TYPE between", value1, value2, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineTypeNotBetween(String value1, String value2) {
			addCriterion("DICT_DEFINE_TYPE not between", value1, value2, "dictDefineType");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueIsNull() {
			addCriterion("DICT_DEFINE_VALUE is null");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueIsNotNull() {
			addCriterion("DICT_DEFINE_VALUE is not null");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueEqualTo(String value) {
			addCriterion("DICT_DEFINE_VALUE =", value, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueNotEqualTo(String value) {
			addCriterion("DICT_DEFINE_VALUE <>", value, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueGreaterThan(String value) {
			addCriterion("DICT_DEFINE_VALUE >", value, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueGreaterThanOrEqualTo(String value) {
			addCriterion("DICT_DEFINE_VALUE >=", value, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueLessThan(String value) {
			addCriterion("DICT_DEFINE_VALUE <", value, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueLessThanOrEqualTo(String value) {
			addCriterion("DICT_DEFINE_VALUE <=", value, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueLike(String value) {
			addCriterion("DICT_DEFINE_VALUE like", value, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueNotLike(String value) {
			addCriterion("DICT_DEFINE_VALUE not like", value, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueIn(List<String> values) {
			addCriterion("DICT_DEFINE_VALUE in", values, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueNotIn(List<String> values) {
			addCriterion("DICT_DEFINE_VALUE not in", values, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueBetween(String value1, String value2) {
			addCriterion("DICT_DEFINE_VALUE between", value1, value2, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andDictDefineValueNotBetween(String value1, String value2) {
			addCriterion("DICT_DEFINE_VALUE not between", value1, value2, "dictDefineValue");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("REMARK in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("REMARK not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dict_define
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_define
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 15 10:17:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}