package com.whhft.sysmanage.common.entity;

import java.util.ArrayList;
import java.util.List;

public class DictDetailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public DictDetailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDictDetailIdIsNull() {
			addCriterion("DICT_DETAIL_ID is null");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdIsNotNull() {
			addCriterion("DICT_DETAIL_ID is not null");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdEqualTo(Integer value) {
			addCriterion("DICT_DETAIL_ID =", value, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdNotEqualTo(Integer value) {
			addCriterion("DICT_DETAIL_ID <>", value, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdGreaterThan(Integer value) {
			addCriterion("DICT_DETAIL_ID >", value, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("DICT_DETAIL_ID >=", value, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdLessThan(Integer value) {
			addCriterion("DICT_DETAIL_ID <", value, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdLessThanOrEqualTo(Integer value) {
			addCriterion("DICT_DETAIL_ID <=", value, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdIn(List<Integer> values) {
			addCriterion("DICT_DETAIL_ID in", values, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdNotIn(List<Integer> values) {
			addCriterion("DICT_DETAIL_ID not in", values, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdBetween(Integer value1, Integer value2) {
			addCriterion("DICT_DETAIL_ID between", value1, value2, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailIdNotBetween(Integer value1, Integer value2) {
			addCriterion("DICT_DETAIL_ID not between", value1, value2, "dictDetailId");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyIsNull() {
			addCriterion("DICT_DETAIL_KEY is null");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyIsNotNull() {
			addCriterion("DICT_DETAIL_KEY is not null");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyEqualTo(String value) {
			addCriterion("DICT_DETAIL_KEY =", value, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyNotEqualTo(String value) {
			addCriterion("DICT_DETAIL_KEY <>", value, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyGreaterThan(String value) {
			addCriterion("DICT_DETAIL_KEY >", value, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyGreaterThanOrEqualTo(String value) {
			addCriterion("DICT_DETAIL_KEY >=", value, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyLessThan(String value) {
			addCriterion("DICT_DETAIL_KEY <", value, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyLessThanOrEqualTo(String value) {
			addCriterion("DICT_DETAIL_KEY <=", value, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyLike(String value) {
			addCriterion("DICT_DETAIL_KEY like", value, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyNotLike(String value) {
			addCriterion("DICT_DETAIL_KEY not like", value, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyIn(List<String> values) {
			addCriterion("DICT_DETAIL_KEY in", values, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyNotIn(List<String> values) {
			addCriterion("DICT_DETAIL_KEY not in", values, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyBetween(String value1, String value2) {
			addCriterion("DICT_DETAIL_KEY between", value1, value2, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailKeyNotBetween(String value1, String value2) {
			addCriterion("DICT_DETAIL_KEY not between", value1, value2, "dictDetailKey");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameIsNull() {
			addCriterion("DICT_DETAIL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameIsNotNull() {
			addCriterion("DICT_DETAIL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameEqualTo(String value) {
			addCriterion("DICT_DETAIL_NAME =", value, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameNotEqualTo(String value) {
			addCriterion("DICT_DETAIL_NAME <>", value, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameGreaterThan(String value) {
			addCriterion("DICT_DETAIL_NAME >", value, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameGreaterThanOrEqualTo(String value) {
			addCriterion("DICT_DETAIL_NAME >=", value, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameLessThan(String value) {
			addCriterion("DICT_DETAIL_NAME <", value, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameLessThanOrEqualTo(String value) {
			addCriterion("DICT_DETAIL_NAME <=", value, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameLike(String value) {
			addCriterion("DICT_DETAIL_NAME like", value, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameNotLike(String value) {
			addCriterion("DICT_DETAIL_NAME not like", value, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameIn(List<String> values) {
			addCriterion("DICT_DETAIL_NAME in", values, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameNotIn(List<String> values) {
			addCriterion("DICT_DETAIL_NAME not in", values, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameBetween(String value1, String value2) {
			addCriterion("DICT_DETAIL_NAME between", value1, value2, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailNameNotBetween(String value1, String value2) {
			addCriterion("DICT_DETAIL_NAME not between", value1, value2, "dictDetailName");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueIsNull() {
			addCriterion("DICT_DETAIL_VALUE is null");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueIsNotNull() {
			addCriterion("DICT_DETAIL_VALUE is not null");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueEqualTo(String value) {
			addCriterion("DICT_DETAIL_VALUE =", value, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueNotEqualTo(String value) {
			addCriterion("DICT_DETAIL_VALUE <>", value, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueGreaterThan(String value) {
			addCriterion("DICT_DETAIL_VALUE >", value, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueGreaterThanOrEqualTo(String value) {
			addCriterion("DICT_DETAIL_VALUE >=", value, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueLessThan(String value) {
			addCriterion("DICT_DETAIL_VALUE <", value, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueLessThanOrEqualTo(String value) {
			addCriterion("DICT_DETAIL_VALUE <=", value, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueLike(String value) {
			addCriterion("DICT_DETAIL_VALUE like", value, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueNotLike(String value) {
			addCriterion("DICT_DETAIL_VALUE not like", value, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueIn(List<String> values) {
			addCriterion("DICT_DETAIL_VALUE in", values, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueNotIn(List<String> values) {
			addCriterion("DICT_DETAIL_VALUE not in", values, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueBetween(String value1, String value2) {
			addCriterion("DICT_DETAIL_VALUE between", value1, value2, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andDictDetailValueNotBetween(String value1, String value2) {
			addCriterion("DICT_DETAIL_VALUE not between", value1, value2, "dictDetailValue");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("REMARK in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("REMARK not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdIsNull() {
			addCriterion("DICT_DEFINE_ID is null");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdIsNotNull() {
			addCriterion("DICT_DEFINE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdEqualTo(Integer value) {
			addCriterion("DICT_DEFINE_ID =", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdNotEqualTo(Integer value) {
			addCriterion("DICT_DEFINE_ID <>", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdGreaterThan(Integer value) {
			addCriterion("DICT_DEFINE_ID >", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("DICT_DEFINE_ID >=", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdLessThan(Integer value) {
			addCriterion("DICT_DEFINE_ID <", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdLessThanOrEqualTo(Integer value) {
			addCriterion("DICT_DEFINE_ID <=", value, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdIn(List<Integer> values) {
			addCriterion("DICT_DEFINE_ID in", values, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdNotIn(List<Integer> values) {
			addCriterion("DICT_DEFINE_ID not in", values, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdBetween(Integer value1, Integer value2) {
			addCriterion("DICT_DEFINE_ID between", value1, value2, "dictDefineId");
			return (Criteria) this;
		}

		public Criteria andDictDefineIdNotBetween(Integer value1, Integer value2) {
			addCriterion("DICT_DEFINE_ID not between", value1, value2, "dictDefineId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dict_detail
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_detail
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 15 10:17:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}