package com.whhft.sysmanage.common.entity;

import javax.validation.constraints.Size;

import com.whhft.sysmanage.common.base.BaseEntity;

public class DictDetail extends BaseEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dict_detail.DICT_DETAIL_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer dictDetailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dict_detail.DICT_DETAIL_KEY
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	@Size(min=6,max=20,message="密码长度不合适")
	private String dictDetailKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dict_detail.DICT_DETAIL_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String dictDetailName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dict_detail.DICT_DETAIL_VALUE
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String dictDetailValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dict_detail.REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dict_detail.DICT_DEFINE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer dictDefineId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dict_detail.DICT_DETAIL_ID
	 * @return  the value of dict_detail.DICT_DETAIL_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getDictDetailId() {
		return dictDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dict_detail.DICT_DETAIL_ID
	 * @param dictDetailId  the value for dict_detail.DICT_DETAIL_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDictDetailId(Integer dictDetailId) {
		this.dictDetailId = dictDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dict_detail.DICT_DETAIL_KEY
	 * @return  the value of dict_detail.DICT_DETAIL_KEY
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getDictDetailKey() {
		return dictDetailKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dict_detail.DICT_DETAIL_KEY
	 * @param dictDetailKey  the value for dict_detail.DICT_DETAIL_KEY
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDictDetailKey(String dictDetailKey) {
		this.dictDetailKey = dictDetailKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dict_detail.DICT_DETAIL_NAME
	 * @return  the value of dict_detail.DICT_DETAIL_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getDictDetailName() {
		return dictDetailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dict_detail.DICT_DETAIL_NAME
	 * @param dictDetailName  the value for dict_detail.DICT_DETAIL_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDictDetailName(String dictDetailName) {
		this.dictDetailName = dictDetailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dict_detail.DICT_DETAIL_VALUE
	 * @return  the value of dict_detail.DICT_DETAIL_VALUE
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getDictDetailValue() {
		return dictDetailValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dict_detail.DICT_DETAIL_VALUE
	 * @param dictDetailValue  the value for dict_detail.DICT_DETAIL_VALUE
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDictDetailValue(String dictDetailValue) {
		this.dictDetailValue = dictDetailValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dict_detail.REMARK
	 * @return  the value of dict_detail.REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dict_detail.REMARK
	 * @param remark  the value for dict_detail.REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dict_detail.DICT_DEFINE_ID
	 * @return  the value of dict_detail.DICT_DEFINE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getDictDefineId() {
		return dictDefineId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dict_detail.DICT_DEFINE_ID
	 * @param dictDefineId  the value for dict_detail.DICT_DEFINE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDictDefineId(Integer dictDefineId) {
		this.dictDefineId = dictDefineId;
	}
}