package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class NewsCatalog extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.catalog_id
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    private Integer catalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.catalog_name
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    private String catalogName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.parent_catalog_id
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    private Integer parentCatalogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.order_no
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_catalog.remark
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.catalog_id
     *
     * @return the value of news_catalog.catalog_id
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public Integer getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.catalog_id
     *
     * @param catalogId the value for news_catalog.catalog_id
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public void setCatalogId(Integer catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.catalog_name
     *
     * @return the value of news_catalog.catalog_name
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public String getCatalogName() {
        return catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.catalog_name
     *
     * @param catalogName the value for news_catalog.catalog_name
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.parent_catalog_id
     *
     * @return the value of news_catalog.parent_catalog_id
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public Integer getParentCatalogId() {
        return parentCatalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.parent_catalog_id
     *
     * @param parentCatalogId the value for news_catalog.parent_catalog_id
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public void setParentCatalogId(Integer parentCatalogId) {
        this.parentCatalogId = parentCatalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.order_no
     *
     * @return the value of news_catalog.order_no
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.order_no
     *
     * @param orderNo the value for news_catalog.order_no
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_catalog.remark
     *
     * @return the value of news_catalog.remark
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_catalog.remark
     *
     * @param remark the value for news_catalog.remark
     *
     * @mbggenerated Thu Nov 09 13:08:12 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}