package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class RoleAuthRs extends BaseEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_auth_rs.AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer authId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_auth_rs.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_auth_rs.AUTH_ID
	 * @return  the value of role_auth_rs.AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getAuthId() {
		return authId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_auth_rs.AUTH_ID
	 * @param authId  the value for role_auth_rs.AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setAuthId(Integer authId) {
		this.authId = authId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_auth_rs.ROLE_ID
	 * @return  the value of role_auth_rs.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_auth_rs.ROLE_ID
	 * @param roleId  the value for role_auth_rs.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}