package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class ServerInfo extends BaseEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_info.server_info_id
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Long serverInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_info.cpu_use_rate
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Double cpuUseRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_info.mem_size
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Long memSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_info.mem_use_rate
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Double memUseRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column server_info.server_time
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String serverTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_info.server_info_id
	 * @return  the value of server_info.server_info_id
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Long getServerInfoId() {
		return serverInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_info.server_info_id
	 * @param serverInfoId  the value for server_info.server_info_id
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setServerInfoId(Long serverInfoId) {
		this.serverInfoId = serverInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_info.cpu_use_rate
	 * @return  the value of server_info.cpu_use_rate
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Double getCpuUseRate() {
		return cpuUseRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_info.cpu_use_rate
	 * @param cpuUseRate  the value for server_info.cpu_use_rate
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setCpuUseRate(Double cpuUseRate) {
		this.cpuUseRate = cpuUseRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_info.mem_size
	 * @return  the value of server_info.mem_size
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Long getMemSize() {
		return memSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_info.mem_size
	 * @param memSize  the value for server_info.mem_size
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setMemSize(Long memSize) {
		this.memSize = memSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_info.mem_use_rate
	 * @return  the value of server_info.mem_use_rate
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Double getMemUseRate() {
		return memUseRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_info.mem_use_rate
	 * @param memUseRate  the value for server_info.mem_use_rate
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setMemUseRate(Double memUseRate) {
		this.memUseRate = memUseRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column server_info.server_time
	 * @return  the value of server_info.server_time
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getServerTime() {
		return serverTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column server_info.server_time
	 * @param serverTime  the value for server_info.server_time
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setServerTime(String serverTime) {
		this.serverTime = serverTime;
	}
}