package com.whhft.sysmanage.common.entity;

import java.util.ArrayList;
import java.util.List;

public class ServerInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public ServerInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andServerInfoIdIsNull() {
			addCriterion("server_info_id is null");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdIsNotNull() {
			addCriterion("server_info_id is not null");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdEqualTo(Long value) {
			addCriterion("server_info_id =", value, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdNotEqualTo(Long value) {
			addCriterion("server_info_id <>", value, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdGreaterThan(Long value) {
			addCriterion("server_info_id >", value, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdGreaterThanOrEqualTo(Long value) {
			addCriterion("server_info_id >=", value, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdLessThan(Long value) {
			addCriterion("server_info_id <", value, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdLessThanOrEqualTo(Long value) {
			addCriterion("server_info_id <=", value, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdIn(List<Long> values) {
			addCriterion("server_info_id in", values, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdNotIn(List<Long> values) {
			addCriterion("server_info_id not in", values, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdBetween(Long value1, Long value2) {
			addCriterion("server_info_id between", value1, value2, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andServerInfoIdNotBetween(Long value1, Long value2) {
			addCriterion("server_info_id not between", value1, value2, "serverInfoId");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateIsNull() {
			addCriterion("cpu_use_rate is null");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateIsNotNull() {
			addCriterion("cpu_use_rate is not null");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateEqualTo(Double value) {
			addCriterion("cpu_use_rate =", value, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateNotEqualTo(Double value) {
			addCriterion("cpu_use_rate <>", value, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateGreaterThan(Double value) {
			addCriterion("cpu_use_rate >", value, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateGreaterThanOrEqualTo(Double value) {
			addCriterion("cpu_use_rate >=", value, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateLessThan(Double value) {
			addCriterion("cpu_use_rate <", value, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateLessThanOrEqualTo(Double value) {
			addCriterion("cpu_use_rate <=", value, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateIn(List<Double> values) {
			addCriterion("cpu_use_rate in", values, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateNotIn(List<Double> values) {
			addCriterion("cpu_use_rate not in", values, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateBetween(Double value1, Double value2) {
			addCriterion("cpu_use_rate between", value1, value2, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andCpuUseRateNotBetween(Double value1, Double value2) {
			addCriterion("cpu_use_rate not between", value1, value2, "cpuUseRate");
			return (Criteria) this;
		}

		public Criteria andMemSizeIsNull() {
			addCriterion("mem_size is null");
			return (Criteria) this;
		}

		public Criteria andMemSizeIsNotNull() {
			addCriterion("mem_size is not null");
			return (Criteria) this;
		}

		public Criteria andMemSizeEqualTo(Long value) {
			addCriterion("mem_size =", value, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeNotEqualTo(Long value) {
			addCriterion("mem_size <>", value, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeGreaterThan(Long value) {
			addCriterion("mem_size >", value, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeGreaterThanOrEqualTo(Long value) {
			addCriterion("mem_size >=", value, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeLessThan(Long value) {
			addCriterion("mem_size <", value, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeLessThanOrEqualTo(Long value) {
			addCriterion("mem_size <=", value, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeIn(List<Long> values) {
			addCriterion("mem_size in", values, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeNotIn(List<Long> values) {
			addCriterion("mem_size not in", values, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeBetween(Long value1, Long value2) {
			addCriterion("mem_size between", value1, value2, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemSizeNotBetween(Long value1, Long value2) {
			addCriterion("mem_size not between", value1, value2, "memSize");
			return (Criteria) this;
		}

		public Criteria andMemUseRateIsNull() {
			addCriterion("mem_use_rate is null");
			return (Criteria) this;
		}

		public Criteria andMemUseRateIsNotNull() {
			addCriterion("mem_use_rate is not null");
			return (Criteria) this;
		}

		public Criteria andMemUseRateEqualTo(Double value) {
			addCriterion("mem_use_rate =", value, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateNotEqualTo(Double value) {
			addCriterion("mem_use_rate <>", value, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateGreaterThan(Double value) {
			addCriterion("mem_use_rate >", value, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateGreaterThanOrEqualTo(Double value) {
			addCriterion("mem_use_rate >=", value, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateLessThan(Double value) {
			addCriterion("mem_use_rate <", value, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateLessThanOrEqualTo(Double value) {
			addCriterion("mem_use_rate <=", value, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateIn(List<Double> values) {
			addCriterion("mem_use_rate in", values, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateNotIn(List<Double> values) {
			addCriterion("mem_use_rate not in", values, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateBetween(Double value1, Double value2) {
			addCriterion("mem_use_rate between", value1, value2, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andMemUseRateNotBetween(Double value1, Double value2) {
			addCriterion("mem_use_rate not between", value1, value2, "memUseRate");
			return (Criteria) this;
		}

		public Criteria andServerTimeIsNull() {
			addCriterion("server_time is null");
			return (Criteria) this;
		}

		public Criteria andServerTimeIsNotNull() {
			addCriterion("server_time is not null");
			return (Criteria) this;
		}

		public Criteria andServerTimeEqualTo(String value) {
			addCriterion("server_time =", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeNotEqualTo(String value) {
			addCriterion("server_time <>", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeGreaterThan(String value) {
			addCriterion("server_time >", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeGreaterThanOrEqualTo(String value) {
			addCriterion("server_time >=", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeLessThan(String value) {
			addCriterion("server_time <", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeLessThanOrEqualTo(String value) {
			addCriterion("server_time <=", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeLike(String value) {
			addCriterion("server_time like", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeNotLike(String value) {
			addCriterion("server_time not like", value, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeIn(List<String> values) {
			addCriterion("server_time in", values, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeNotIn(List<String> values) {
			addCriterion("server_time not in", values, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeBetween(String value1, String value2) {
			addCriterion("server_time between", value1, value2, "serverTime");
			return (Criteria) this;
		}

		public Criteria andServerTimeNotBetween(String value1, String value2) {
			addCriterion("server_time not between", value1, value2, "serverTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table server_info
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table server_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 15 10:17:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}