package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class SysAuth extends BaseEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer authId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.AUTH_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String authName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.ORDER_NO
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.PARENT_AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer parentAuthId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.RESOURCES
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String resources;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.AUTH_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String authUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.ENABLED
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String enabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.ICON_STYLE
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String iconStyle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_auth.LEAF
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String leaf;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.AUTH_ID
	 * @return  the value of sys_auth.AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getAuthId() {
		return authId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.AUTH_ID
	 * @param authId  the value for sys_auth.AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setAuthId(Integer authId) {
		this.authId = authId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.AUTH_NAME
	 * @return  the value of sys_auth.AUTH_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getAuthName() {
		return authName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.AUTH_NAME
	 * @param authName  the value for sys_auth.AUTH_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setAuthName(String authName) {
		this.authName = authName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.REMARK
	 * @return  the value of sys_auth.REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.REMARK
	 * @param remark  the value for sys_auth.REMARK
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.ORDER_NO
	 * @return  the value of sys_auth.ORDER_NO
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.ORDER_NO
	 * @param orderNo  the value for sys_auth.ORDER_NO
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.PARENT_AUTH_ID
	 * @return  the value of sys_auth.PARENT_AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getParentAuthId() {
		return parentAuthId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.PARENT_AUTH_ID
	 * @param parentAuthId  the value for sys_auth.PARENT_AUTH_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setParentAuthId(Integer parentAuthId) {
		this.parentAuthId = parentAuthId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.RESOURCES
	 * @return  the value of sys_auth.RESOURCES
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getResources() {
		return resources;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.RESOURCES
	 * @param resources  the value for sys_auth.RESOURCES
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setResources(String resources) {
		this.resources = resources;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.AUTH_URL
	 * @return  the value of sys_auth.AUTH_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getAuthUrl() {
		return authUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.AUTH_URL
	 * @param authUrl  the value for sys_auth.AUTH_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setAuthUrl(String authUrl) {
		this.authUrl = authUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.ENABLED
	 * @return  the value of sys_auth.ENABLED
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.ENABLED
	 * @param enabled  the value for sys_auth.ENABLED
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.ICON_STYLE
	 * @return  the value of sys_auth.ICON_STYLE
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getIconStyle() {
		return iconStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.ICON_STYLE
	 * @param iconStyle  the value for sys_auth.ICON_STYLE
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setIconStyle(String iconStyle) {
		this.iconStyle = iconStyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_auth.LEAF
	 * @return  the value of sys_auth.LEAF
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getLeaf() {
		return leaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_auth.LEAF
	 * @param leaf  the value for sys_auth.LEAF
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setLeaf(String leaf) {
		this.leaf = leaf;
	}
}