package com.whhft.sysmanage.common.entity;

import java.util.ArrayList;
import java.util.List;

public class SysAuthExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public SysAuthExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAuthIdIsNull() {
			addCriterion("AUTH_ID is null");
			return (Criteria) this;
		}

		public Criteria andAuthIdIsNotNull() {
			addCriterion("AUTH_ID is not null");
			return (Criteria) this;
		}

		public Criteria andAuthIdEqualTo(Integer value) {
			addCriterion("AUTH_ID =", value, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdNotEqualTo(Integer value) {
			addCriterion("AUTH_ID <>", value, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdGreaterThan(Integer value) {
			addCriterion("AUTH_ID >", value, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("AUTH_ID >=", value, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdLessThan(Integer value) {
			addCriterion("AUTH_ID <", value, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdLessThanOrEqualTo(Integer value) {
			addCriterion("AUTH_ID <=", value, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdIn(List<Integer> values) {
			addCriterion("AUTH_ID in", values, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdNotIn(List<Integer> values) {
			addCriterion("AUTH_ID not in", values, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdBetween(Integer value1, Integer value2) {
			addCriterion("AUTH_ID between", value1, value2, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthIdNotBetween(Integer value1, Integer value2) {
			addCriterion("AUTH_ID not between", value1, value2, "authId");
			return (Criteria) this;
		}

		public Criteria andAuthNameIsNull() {
			addCriterion("AUTH_NAME is null");
			return (Criteria) this;
		}

		public Criteria andAuthNameIsNotNull() {
			addCriterion("AUTH_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andAuthNameEqualTo(String value) {
			addCriterion("AUTH_NAME =", value, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameNotEqualTo(String value) {
			addCriterion("AUTH_NAME <>", value, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameGreaterThan(String value) {
			addCriterion("AUTH_NAME >", value, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameGreaterThanOrEqualTo(String value) {
			addCriterion("AUTH_NAME >=", value, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameLessThan(String value) {
			addCriterion("AUTH_NAME <", value, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameLessThanOrEqualTo(String value) {
			addCriterion("AUTH_NAME <=", value, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameLike(String value) {
			addCriterion("AUTH_NAME like", value, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameNotLike(String value) {
			addCriterion("AUTH_NAME not like", value, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameIn(List<String> values) {
			addCriterion("AUTH_NAME in", values, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameNotIn(List<String> values) {
			addCriterion("AUTH_NAME not in", values, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameBetween(String value1, String value2) {
			addCriterion("AUTH_NAME between", value1, value2, "authName");
			return (Criteria) this;
		}

		public Criteria andAuthNameNotBetween(String value1, String value2) {
			addCriterion("AUTH_NAME not between", value1, value2, "authName");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("REMARK is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("REMARK =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("REMARK <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("REMARK >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("REMARK >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("REMARK <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("REMARK <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("REMARK like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("REMARK not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("REMARK in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("REMARK not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("REMARK between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("REMARK not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNull() {
			addCriterion("ORDER_NO is null");
			return (Criteria) this;
		}

		public Criteria andOrderNoIsNotNull() {
			addCriterion("ORDER_NO is not null");
			return (Criteria) this;
		}

		public Criteria andOrderNoEqualTo(Integer value) {
			addCriterion("ORDER_NO =", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotEqualTo(Integer value) {
			addCriterion("ORDER_NO <>", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThan(Integer value) {
			addCriterion("ORDER_NO >", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoGreaterThanOrEqualTo(Integer value) {
			addCriterion("ORDER_NO >=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThan(Integer value) {
			addCriterion("ORDER_NO <", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoLessThanOrEqualTo(Integer value) {
			addCriterion("ORDER_NO <=", value, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoIn(List<Integer> values) {
			addCriterion("ORDER_NO in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotIn(List<Integer> values) {
			addCriterion("ORDER_NO not in", values, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_NO between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andOrderNoNotBetween(Integer value1, Integer value2) {
			addCriterion("ORDER_NO not between", value1, value2, "orderNo");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdIsNull() {
			addCriterion("PARENT_AUTH_ID is null");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdIsNotNull() {
			addCriterion("PARENT_AUTH_ID is not null");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdEqualTo(Integer value) {
			addCriterion("PARENT_AUTH_ID =", value, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdNotEqualTo(Integer value) {
			addCriterion("PARENT_AUTH_ID <>", value, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdGreaterThan(Integer value) {
			addCriterion("PARENT_AUTH_ID >", value, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PARENT_AUTH_ID >=", value, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdLessThan(Integer value) {
			addCriterion("PARENT_AUTH_ID <", value, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdLessThanOrEqualTo(Integer value) {
			addCriterion("PARENT_AUTH_ID <=", value, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdIn(List<Integer> values) {
			addCriterion("PARENT_AUTH_ID in", values, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdNotIn(List<Integer> values) {
			addCriterion("PARENT_AUTH_ID not in", values, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdBetween(Integer value1, Integer value2) {
			addCriterion("PARENT_AUTH_ID between", value1, value2, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andParentAuthIdNotBetween(Integer value1, Integer value2) {
			addCriterion("PARENT_AUTH_ID not between", value1, value2, "parentAuthId");
			return (Criteria) this;
		}

		public Criteria andResourcesIsNull() {
			addCriterion("RESOURCES is null");
			return (Criteria) this;
		}

		public Criteria andResourcesIsNotNull() {
			addCriterion("RESOURCES is not null");
			return (Criteria) this;
		}

		public Criteria andResourcesEqualTo(String value) {
			addCriterion("RESOURCES =", value, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesNotEqualTo(String value) {
			addCriterion("RESOURCES <>", value, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesGreaterThan(String value) {
			addCriterion("RESOURCES >", value, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesGreaterThanOrEqualTo(String value) {
			addCriterion("RESOURCES >=", value, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesLessThan(String value) {
			addCriterion("RESOURCES <", value, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesLessThanOrEqualTo(String value) {
			addCriterion("RESOURCES <=", value, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesLike(String value) {
			addCriterion("RESOURCES like", value, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesNotLike(String value) {
			addCriterion("RESOURCES not like", value, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesIn(List<String> values) {
			addCriterion("RESOURCES in", values, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesNotIn(List<String> values) {
			addCriterion("RESOURCES not in", values, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesBetween(String value1, String value2) {
			addCriterion("RESOURCES between", value1, value2, "resources");
			return (Criteria) this;
		}

		public Criteria andResourcesNotBetween(String value1, String value2) {
			addCriterion("RESOURCES not between", value1, value2, "resources");
			return (Criteria) this;
		}

		public Criteria andAuthUrlIsNull() {
			addCriterion("AUTH_URL is null");
			return (Criteria) this;
		}

		public Criteria andAuthUrlIsNotNull() {
			addCriterion("AUTH_URL is not null");
			return (Criteria) this;
		}

		public Criteria andAuthUrlEqualTo(String value) {
			addCriterion("AUTH_URL =", value, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlNotEqualTo(String value) {
			addCriterion("AUTH_URL <>", value, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlGreaterThan(String value) {
			addCriterion("AUTH_URL >", value, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlGreaterThanOrEqualTo(String value) {
			addCriterion("AUTH_URL >=", value, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlLessThan(String value) {
			addCriterion("AUTH_URL <", value, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlLessThanOrEqualTo(String value) {
			addCriterion("AUTH_URL <=", value, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlLike(String value) {
			addCriterion("AUTH_URL like", value, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlNotLike(String value) {
			addCriterion("AUTH_URL not like", value, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlIn(List<String> values) {
			addCriterion("AUTH_URL in", values, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlNotIn(List<String> values) {
			addCriterion("AUTH_URL not in", values, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlBetween(String value1, String value2) {
			addCriterion("AUTH_URL between", value1, value2, "authUrl");
			return (Criteria) this;
		}

		public Criteria andAuthUrlNotBetween(String value1, String value2) {
			addCriterion("AUTH_URL not between", value1, value2, "authUrl");
			return (Criteria) this;
		}

		public Criteria andEnabledIsNull() {
			addCriterion("ENABLED is null");
			return (Criteria) this;
		}

		public Criteria andEnabledIsNotNull() {
			addCriterion("ENABLED is not null");
			return (Criteria) this;
		}

		public Criteria andEnabledEqualTo(String value) {
			addCriterion("ENABLED =", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotEqualTo(String value) {
			addCriterion("ENABLED <>", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledGreaterThan(String value) {
			addCriterion("ENABLED >", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledGreaterThanOrEqualTo(String value) {
			addCriterion("ENABLED >=", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLessThan(String value) {
			addCriterion("ENABLED <", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLessThanOrEqualTo(String value) {
			addCriterion("ENABLED <=", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledLike(String value) {
			addCriterion("ENABLED like", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotLike(String value) {
			addCriterion("ENABLED not like", value, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledIn(List<String> values) {
			addCriterion("ENABLED in", values, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotIn(List<String> values) {
			addCriterion("ENABLED not in", values, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledBetween(String value1, String value2) {
			addCriterion("ENABLED between", value1, value2, "enabled");
			return (Criteria) this;
		}

		public Criteria andEnabledNotBetween(String value1, String value2) {
			addCriterion("ENABLED not between", value1, value2, "enabled");
			return (Criteria) this;
		}

		public Criteria andIconStyleIsNull() {
			addCriterion("ICON_STYLE is null");
			return (Criteria) this;
		}

		public Criteria andIconStyleIsNotNull() {
			addCriterion("ICON_STYLE is not null");
			return (Criteria) this;
		}

		public Criteria andIconStyleEqualTo(String value) {
			addCriterion("ICON_STYLE =", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleNotEqualTo(String value) {
			addCriterion("ICON_STYLE <>", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleGreaterThan(String value) {
			addCriterion("ICON_STYLE >", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleGreaterThanOrEqualTo(String value) {
			addCriterion("ICON_STYLE >=", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleLessThan(String value) {
			addCriterion("ICON_STYLE <", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleLessThanOrEqualTo(String value) {
			addCriterion("ICON_STYLE <=", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleLike(String value) {
			addCriterion("ICON_STYLE like", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleNotLike(String value) {
			addCriterion("ICON_STYLE not like", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleIn(List<String> values) {
			addCriterion("ICON_STYLE in", values, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleNotIn(List<String> values) {
			addCriterion("ICON_STYLE not in", values, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleBetween(String value1, String value2) {
			addCriterion("ICON_STYLE between", value1, value2, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleNotBetween(String value1, String value2) {
			addCriterion("ICON_STYLE not between", value1, value2, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andLeafIsNull() {
			addCriterion("LEAF is null");
			return (Criteria) this;
		}

		public Criteria andLeafIsNotNull() {
			addCriterion("LEAF is not null");
			return (Criteria) this;
		}

		public Criteria andLeafEqualTo(String value) {
			addCriterion("LEAF =", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafNotEqualTo(String value) {
			addCriterion("LEAF <>", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafGreaterThan(String value) {
			addCriterion("LEAF >", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafGreaterThanOrEqualTo(String value) {
			addCriterion("LEAF >=", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafLessThan(String value) {
			addCriterion("LEAF <", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafLessThanOrEqualTo(String value) {
			addCriterion("LEAF <=", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafLike(String value) {
			addCriterion("LEAF like", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafNotLike(String value) {
			addCriterion("LEAF not like", value, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafIn(List<String> values) {
			addCriterion("LEAF in", values, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafNotIn(List<String> values) {
			addCriterion("LEAF not in", values, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafBetween(String value1, String value2) {
			addCriterion("LEAF between", value1, value2, "leaf");
			return (Criteria) this;
		}

		public Criteria andLeafNotBetween(String value1, String value2) {
			addCriterion("LEAF not between", value1, value2, "leaf");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_auth
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_auth
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 15 10:17:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}