package com.whhft.sysmanage.common.entity;

import java.util.ArrayList;
import java.util.List;

public class SysLogExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public SysLogExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andLogIdIsNull() {
			addCriterion("LOG_ID is null");
			return (Criteria) this;
		}

		public Criteria andLogIdIsNotNull() {
			addCriterion("LOG_ID is not null");
			return (Criteria) this;
		}

		public Criteria andLogIdEqualTo(Integer value) {
			addCriterion("LOG_ID =", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotEqualTo(Integer value) {
			addCriterion("LOG_ID <>", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThan(Integer value) {
			addCriterion("LOG_ID >", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("LOG_ID >=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThan(Integer value) {
			addCriterion("LOG_ID <", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdLessThanOrEqualTo(Integer value) {
			addCriterion("LOG_ID <=", value, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdIn(List<Integer> values) {
			addCriterion("LOG_ID in", values, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotIn(List<Integer> values) {
			addCriterion("LOG_ID not in", values, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdBetween(Integer value1, Integer value2) {
			addCriterion("LOG_ID between", value1, value2, "logId");
			return (Criteria) this;
		}

		public Criteria andLogIdNotBetween(Integer value1, Integer value2) {
			addCriterion("LOG_ID not between", value1, value2, "logId");
			return (Criteria) this;
		}

		public Criteria andActionParamsIsNull() {
			addCriterion("ACTION_PARAMS is null");
			return (Criteria) this;
		}

		public Criteria andActionParamsIsNotNull() {
			addCriterion("ACTION_PARAMS is not null");
			return (Criteria) this;
		}

		public Criteria andActionParamsEqualTo(String value) {
			addCriterion("ACTION_PARAMS =", value, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsNotEqualTo(String value) {
			addCriterion("ACTION_PARAMS <>", value, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsGreaterThan(String value) {
			addCriterion("ACTION_PARAMS >", value, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsGreaterThanOrEqualTo(String value) {
			addCriterion("ACTION_PARAMS >=", value, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsLessThan(String value) {
			addCriterion("ACTION_PARAMS <", value, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsLessThanOrEqualTo(String value) {
			addCriterion("ACTION_PARAMS <=", value, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsLike(String value) {
			addCriterion("ACTION_PARAMS like", value, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsNotLike(String value) {
			addCriterion("ACTION_PARAMS not like", value, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsIn(List<String> values) {
			addCriterion("ACTION_PARAMS in", values, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsNotIn(List<String> values) {
			addCriterion("ACTION_PARAMS not in", values, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsBetween(String value1, String value2) {
			addCriterion("ACTION_PARAMS between", value1, value2, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionParamsNotBetween(String value1, String value2) {
			addCriterion("ACTION_PARAMS not between", value1, value2, "actionParams");
			return (Criteria) this;
		}

		public Criteria andActionUrlIsNull() {
			addCriterion("ACTION_URL is null");
			return (Criteria) this;
		}

		public Criteria andActionUrlIsNotNull() {
			addCriterion("ACTION_URL is not null");
			return (Criteria) this;
		}

		public Criteria andActionUrlEqualTo(String value) {
			addCriterion("ACTION_URL =", value, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlNotEqualTo(String value) {
			addCriterion("ACTION_URL <>", value, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlGreaterThan(String value) {
			addCriterion("ACTION_URL >", value, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlGreaterThanOrEqualTo(String value) {
			addCriterion("ACTION_URL >=", value, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlLessThan(String value) {
			addCriterion("ACTION_URL <", value, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlLessThanOrEqualTo(String value) {
			addCriterion("ACTION_URL <=", value, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlLike(String value) {
			addCriterion("ACTION_URL like", value, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlNotLike(String value) {
			addCriterion("ACTION_URL not like", value, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlIn(List<String> values) {
			addCriterion("ACTION_URL in", values, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlNotIn(List<String> values) {
			addCriterion("ACTION_URL not in", values, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlBetween(String value1, String value2) {
			addCriterion("ACTION_URL between", value1, value2, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andActionUrlNotBetween(String value1, String value2) {
			addCriterion("ACTION_URL not between", value1, value2, "actionUrl");
			return (Criteria) this;
		}

		public Criteria andLogTimeIsNull() {
			addCriterion("LOG_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLogTimeIsNotNull() {
			addCriterion("LOG_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLogTimeEqualTo(String value) {
			addCriterion("LOG_TIME =", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeNotEqualTo(String value) {
			addCriterion("LOG_TIME <>", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeGreaterThan(String value) {
			addCriterion("LOG_TIME >", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeGreaterThanOrEqualTo(String value) {
			addCriterion("LOG_TIME >=", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeLessThan(String value) {
			addCriterion("LOG_TIME <", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeLessThanOrEqualTo(String value) {
			addCriterion("LOG_TIME <=", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeLike(String value) {
			addCriterion("LOG_TIME like", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeNotLike(String value) {
			addCriterion("LOG_TIME not like", value, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeIn(List<String> values) {
			addCriterion("LOG_TIME in", values, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeNotIn(List<String> values) {
			addCriterion("LOG_TIME not in", values, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeBetween(String value1, String value2) {
			addCriterion("LOG_TIME between", value1, value2, "logTime");
			return (Criteria) this;
		}

		public Criteria andLogTimeNotBetween(String value1, String value2) {
			addCriterion("LOG_TIME not between", value1, value2, "logTime");
			return (Criteria) this;
		}

		public Criteria andUserIpIsNull() {
			addCriterion("USER_IP is null");
			return (Criteria) this;
		}

		public Criteria andUserIpIsNotNull() {
			addCriterion("USER_IP is not null");
			return (Criteria) this;
		}

		public Criteria andUserIpEqualTo(String value) {
			addCriterion("USER_IP =", value, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpNotEqualTo(String value) {
			addCriterion("USER_IP <>", value, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpGreaterThan(String value) {
			addCriterion("USER_IP >", value, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpGreaterThanOrEqualTo(String value) {
			addCriterion("USER_IP >=", value, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpLessThan(String value) {
			addCriterion("USER_IP <", value, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpLessThanOrEqualTo(String value) {
			addCriterion("USER_IP <=", value, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpLike(String value) {
			addCriterion("USER_IP like", value, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpNotLike(String value) {
			addCriterion("USER_IP not like", value, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpIn(List<String> values) {
			addCriterion("USER_IP in", values, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpNotIn(List<String> values) {
			addCriterion("USER_IP not in", values, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpBetween(String value1, String value2) {
			addCriterion("USER_IP between", value1, value2, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIpNotBetween(String value1, String value2) {
			addCriterion("USER_IP not between", value1, value2, "userIp");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("USER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("USER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Integer value) {
			addCriterion("USER_ID =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Integer value) {
			addCriterion("USER_ID <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Integer value) {
			addCriterion("USER_ID >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("USER_ID >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Integer value) {
			addCriterion("USER_ID <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("USER_ID <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Integer> values) {
			addCriterion("USER_ID in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Integer> values) {
			addCriterion("USER_ID not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Integer value1, Integer value2) {
			addCriterion("USER_ID between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("USER_ID not between", value1, value2, "userId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sys_log
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_log
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 15 10:17:21 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}