package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class SysLog extends BaseEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.LOG_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.ACTION_PARAMS
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String actionParams;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.ACTION_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String actionUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.LOG_TIME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String logTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.USER_IP
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String userIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_log.USER_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.LOG_ID
	 * @return  the value of sys_log.LOG_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.LOG_ID
	 * @param logId  the value for sys_log.LOG_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.ACTION_PARAMS
	 * @return  the value of sys_log.ACTION_PARAMS
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getActionParams() {
		return actionParams;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.ACTION_PARAMS
	 * @param actionParams  the value for sys_log.ACTION_PARAMS
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setActionParams(String actionParams) {
		this.actionParams = actionParams;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.ACTION_URL
	 * @return  the value of sys_log.ACTION_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getActionUrl() {
		return actionUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.ACTION_URL
	 * @param actionUrl  the value for sys_log.ACTION_URL
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setActionUrl(String actionUrl) {
		this.actionUrl = actionUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.LOG_TIME
	 * @return  the value of sys_log.LOG_TIME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getLogTime() {
		return logTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.LOG_TIME
	 * @param logTime  the value for sys_log.LOG_TIME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setLogTime(String logTime) {
		this.logTime = logTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.USER_IP
	 * @return  the value of sys_log.USER_IP
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getUserIp() {
		return userIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.USER_IP
	 * @param userIp  the value for sys_log.USER_IP
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_log.USER_ID
	 * @return  the value of sys_log.USER_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_log.USER_ID
	 * @param userId  the value for sys_log.USER_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}