package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class SysRole extends BaseEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.ROLE_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private String roleName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.ROLE_ID
	 * @return  the value of sys_role.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.ROLE_ID
	 * @param roleId  the value for sys_role.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.ROLE_NAME
	 * @return  the value of sys_role.ROLE_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.ROLE_NAME
	 * @param roleName  the value for sys_role.ROLE_NAME
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
}