package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class SysUser extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_ID
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ENABLED
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    private String enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.LOGIN_NAME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.DEL_FLAG
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_NAME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.USER_PWD
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.REMARK
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_ID
     *
     * @return the value of sys_user.USER_ID
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_ID
     *
     * @param userId the value for sys_user.USER_ID
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ENABLED
     *
     * @return the value of sys_user.ENABLED
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ENABLED
     *
     * @param enabled the value for sys_user.ENABLED
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.LOGIN_NAME
     *
     * @return the value of sys_user.LOGIN_NAME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.LOGIN_NAME
     *
     * @param loginName the value for sys_user.LOGIN_NAME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.DEL_FLAG
     *
     * @return the value of sys_user.DEL_FLAG
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.DEL_FLAG
     *
     * @param delFlag the value for sys_user.DEL_FLAG
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATE_TIME
     *
     * @return the value of sys_user.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATE_TIME
     *
     * @param updateTime the value for sys_user.UPDATE_TIME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_NAME
     *
     * @return the value of sys_user.USER_NAME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_NAME
     *
     * @param userName the value for sys_user.USER_NAME
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.USER_PWD
     *
     * @return the value of sys_user.USER_PWD
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.USER_PWD
     *
     * @param userPwd the value for sys_user.USER_PWD
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REMARK
     *
     * @return the value of sys_user.REMARK
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REMARK
     *
     * @param remark the value for sys_user.REMARK
     *
     * @mbg.generated Sun Apr 16 15:11:15 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}