package com.whhft.sysmanage.common.entity;

import com.whhft.sysmanage.common.base.BaseEntity;

public class UserRoleRs extends BaseEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role_rs.USER_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role_rs.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	private Integer roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role_rs.USER_ID
	 * @return  the value of user_role_rs.USER_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role_rs.USER_ID
	 * @param userId  the value for user_role_rs.USER_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role_rs.ROLE_ID
	 * @return  the value of user_role_rs.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role_rs.ROLE_ID
	 * @param roleId  the value for user_role_rs.ROLE_ID
	 * @mbg.generated  Thu Mar 23 17:35:08 CST 2017
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}
}